In [7]:
import tensorflow as tf
tf.__version__


2024-11-25 19:53:15.095974: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1732535595.719317 3528594 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732535595.746249 3528594 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-25 19:53:16.649380: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


'2.18.0'

In [4]:
import torch

torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
import numpy as np

a = np.zeros(5)
print(a)
b = np.zeros(5)
tf.reshape(tf.convert_to_tensor(np.concat([a,b]), dtype=tf.float32), [2,-1])

[0. 0. 0. 0. 0.]


<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [1]:
import tensorflow_probability as tfb

In [15]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()


In [16]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [26]:
predictions = tf.nn.softmax(model(x_train[:1]))

In [27]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [29]:
loss_fn(y_train[:1], predictions)

<tf.Tensor: shape=(), dtype=float32, numpy=2.2876944541931152>

In [31]:
model.compile(
    optimizer = "adam",
    loss = loss_fn,
    metrics = ["accuracy"]
)

In [33]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


I0000 00:00:1731234444.466738 1814121 service.cc:148] XLA service 0x7ff16000a6d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1731234444.466797 1814121 service.cc:156]   StreamExecutor device (0): Tesla V100-PCIE-16GB, Compute Capability 7.0
I0000 00:00:1731234444.466818 1814121 service.cc:156]   StreamExecutor device (1): Tesla V100-PCIE-16GB, Compute Capability 7.0
I0000 00:00:1731234444.466837 1814121 service.cc:156]   StreamExecutor device (2): Tesla V100-PCIE-16GB, Compute Capability 7.0
2024-11-10 18:27:24.498943: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1731234444.560341 1814121 cuda_dnn.cc:529] Loaded cuDNN version 90300


  93/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5358 - loss: 1.4747

I0000 00:00:1731234445.335760 1814121 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8573 - loss: 0.4829
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9550 - loss: 0.1543
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9656 - loss: 0.1119
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9737 - loss: 0.0883
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9762 - loss: 0.0765


In [36]:
model.evaluate(x_test,y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9764 - loss: 0.0713


[0.07127460092306137, 0.9764000177383423]

In [62]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

x_train = x_train[...,tf.newaxis].astype("float32")
x_test = x_test[...,tf.newaxis].astype("float32")

trainds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(10000).batch(32)
testds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)


In [88]:
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

class Mymodel(Model):
    def __init__(self):
        super().__init__()
        self.conv2d = Conv2D(32, 3, activation = "relu")
        self.flatten = Flatten()
        self.d1 = Dense(128, activation="relu")
        self.d2 = Dense(10)

    def call(self, x):
        x = self.conv2d(x)
        x = self.flatten(x)
        x = self.d1(x)
        return self.d2(x)

In [89]:
model = Mymodel()

model

<Mymodel name=mymodel_7, built=False>

In [90]:
loss_obj = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam()

In [91]:
train_loss = tf.keras.metrics.Mean(name="train_loss")
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name="train_accuracy")

test_loss = tf.keras.metrics.Mean(name="test_loss")
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name="test_accuracy")

In [92]:
@tf.function
def train_step(x,y):
    with tf.GradientTape() as tape:
        y_pred = model(x, training=True)
        loss = loss_obj(y,y_pred)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    train_loss(loss)
    train_accuracy(y,y_pred)

@tf.function
def test_step(x,y):
    y_pred = model(x, training=False)
    loss = loss_obj(y,y_pred)

    test_loss(loss)
    test_accuracy(y,y_pred)


In [93]:
EPOCHS = 5

for epoch in range(EPOCHS):
    train_loss.reset_state()
    train_accuracy.reset_state()
    test_loss.reset_state()
    test_accuracy.reset_state()

    for x, y in trainds:
        train_step(x,y)
    
    for x, y in testds:
        test_step(x,y)

    print(f"Finished the {epoch}th epoch:")
    print(f"TrainLoss: {train_loss.result():0.2f}")
    print(f"TrainAccuracy: {train_accuracy.result() * 100 :2f}")
    print(f"TestLoss: {test_loss.result():0.2f}")
    print(f"TestAccuracy: {test_accuracy.result() * 100 :2f}")


Finished the 0th epoch:
TrainLoss: 0.13
TrainAccuracy: 95.983330
TestLoss: 0.06
TestAccuracy: 97.959999
Finished the 1th epoch:
TrainLoss: 0.04
TrainAccuracy: 98.625000
TestLoss: 0.05
TestAccuracy: 98.169998
Finished the 2th epoch:
TrainLoss: 0.02
TrainAccuracy: 99.333336
TestLoss: 0.06
TestAccuracy: 98.269997


KeyboardInterrupt: 

In [66]:
x, y =list(trainds.as_numpy_iterator())[0]

In [69]:
i = model(x, training=True)

In [79]:
i = model(tf.random.normal([32,28,28,1]), training=True)